---
title: "project"
output: html_document
date: "2023-11-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Importing libraries and loading datasets
```{r}
library(tidyverse)
colors = readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-06/colors.csv.gz')
inventories = readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-06/inventories.csv.gz')
inventory_parts = readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-06/inventory_parts.csv.gz')
sets = readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-06/sets.csv.gz')
```

### Joining datasets and selecting columns
```{r}
part_colors = inventory_parts %>%
  left_join(colors, by = c("color_id" = "id")) %>%
  select(-is_spare, -img_url, -is_trans)

sum(is.na(part_colors)) #no missing values

part_colors_set = part_colors %>%
  left_join(inventories, by = c("inventory_id" = "id")) %>% #added "version" and "set_num"
  left_join(sets, by = "set_num", suffix = c("_color", "_set")) %>% #added "name_set" "year" "theme_id" "num_parts" "img_url"
  select(-version, -img_url)
head(part_colors_set)
```

```{r}
summary_stats = part_colors_set %>%
  summarise(
    num_of_uniq_themes = n_distinct(theme_id),
    num_of_uniq_sets = n_distinct(name_set),
    num_of_uniq_colors = n_distinct(color_id),
    least_color = names(which.min(table(name_color))),
    most_color = names(which.max(table(name_color))),
    year_range = paste(min(year, na.rm = TRUE), "-", max(year, na.rm = TRUE)),
    min_num_parts = min(num_parts, na.rm = TRUE),
    max_num_parts = max(num_parts, na.rm = TRUE),
    avg_num_parts = mean(num_parts, na.rm = TRUE)
  )
summary_stats
```





```

```{r}

```


```


```{r}


```


```{r scattrplot}
# find most popular x colours from the entire data set
top_10_colors = part_colors_set %>%
  count(name_color, rgb) %>%
  arrange(desc(n)) %>%
  head(10)

top_10_colors_names = top_10_colors %>% pull(name_color)
top_10_colors_rgb = top_10_colors %>% arrange(name_color) %>% pull(rgb)

# df that contains the number of observations, for the above top 10 colours, for each year
data = part_colors_set %>%
  filter(name_color %in% top_10_colors_names) %>%
  count(year, name_color, wt = quantity)
head(data)

#plotting
ggplot(data = data) +
  geom_point(aes(x = year, y = n, color = name_color)) +
  xlim(1980, 2022) +
  scale_color_manual(values = paste0("#", top_10_colors_rgb)) +
  geom_smooth(aes(x = year, y = n, color = name_color), se = FALSE, size = 0.5) +
  labs(x = "Year", y = "Count", title = "Distribution of the top 10 colors across the year") +
  theme(legend.position = "none")
```

